Kibana
======

Step by step to deploy kibana container into Kubernetes environment.

Quick Start
-----------

[source.console]
----
ğœ† kubectl run kibana --image=kibana:latest --env="ELASTICSEARCH_URL=http://elasticsearch:9200" --port=5601
deployment.apps/kibana created

ğœ† kubectl get deployments
NAME      DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
kibana    1         1         1            1           6m

ğœ† kubectl expose deployment kibana --type=LoadBalancer
service/kibana exposed

ğœ† minikube service list
|-------------|----------------------|--------------------------------|
|  NAMESPACE  |         NAME         |              URL               |
|-------------|----------------------|--------------------------------|
| default     | elasticsearch        | http://192.168.99.100:30920    |
|             |                      | http://192.168.99.100:30930    |
| default     | kibana               | http://192.168.99.100:31232    |
| default     | kubernetes           | No node port                   |
| kube-system | kube-dns             | No node port                   |
| kube-system | kubernetes-dashboard | http://192.168.99.100:30000    |
|-------------|----------------------|--------------------------------|

ğœ† minikube service kibana
Opening kubernetes service default/kibana in default browser...
----


Run Kibana with Kubernetes configurations
-----------------------------------------

[source.console]
----
ğœ† kubectl create -f kibana-deployment.yaml
deployment.apps/kibana created

ğœ† kubectl create -f kibana-service.yaml
service/kibana created
----


References
----------

- Setting up Elasticsearch Cluster on Kubernetes - Part 2 - Kibana, _https://chekkan.com/setting-up-elasticsearch-cluster-on-kubernetes-part-2-kibana/_
- Setting Up Elasticsearch Cluster on Kubernetes - Part 3 - Configuration File, _https://chekkan.com/setting-up-elasticsearch-cluster-on-kubernetes-part-3-config-file/_