apiVersion: v1
kind: Service
metadata:
  name: kibana
  labels:
    run: kibana
spec:
  type: LoadBalancer
  selector:
    run: kibana
  ports:
  - name: http
    port: 5601
    targetPort: 5601
    nodePort: 30560
    protocol: TCP
  externalIPs:
  - 10.0.0.100        