apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: kibana
spec:
  selector:
    matchLabels:
      run: kibana
  template:
    metadata:
      labels:
        run: kibana
    spec:
      containers:
      - name: kibana
        image: kibana:latest
        env:
        - name: ELASTICSEARCH_URL
          value: http://elasticsearch:9200
        ## Kibana 6.x feature  
        # - name: XPACK_SECURITY_ENABLED
          # value: true
        ports:
        - containerPort: 5601
          name: http
          protocol: TCP